name: omni_video_player
description: "A Flutter widget for playing videos from YouTube, Vimeo, assets, and network sources — fully customizable and easy to integrate."
version: 1.0.5
homepage: https://github.com/leonardmatasel/omni_video_player
repository: https://github.com/leonardmatasel/omni_video_player
issue_tracker: https://github.com/leonardmatasel/omni_video_player/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

platforms:
  android:
  ios:
  web:

funding:
  - https://github.com/sponsors/leonardmatasel

dependencies:
  flutter:
    sdk: flutter

  youtube_explode_dart: ^2.5.1
  video_player: ^2.9.5
  wakelock_plus: ^1.3.2
  built_collection: ^5.1.1
  synchronized: ^3.0.1
  flutter_bloc: ^9.1.0
  visibility_detector: ^0.4.0+2
  logger: ^2.5.0
  android_intent_plus: ^5.3.0
  url_launcher: ^6.3.1
  http: ^1.4.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dartdoc: ^8.3.4

topics:
  - video
  - youtube
  - vimeo
  - player
  - video-player